### ISSUE TITLE
PMD incremental analysis

### ISSUE THREAD

**Issue by FHellmann** [novoda/gradle-static-analysis-plugin#104]
I am not sure if this plugin already provide any functionality in this direction, but PMD shows me the message to turn the Incremental Analysis on for a higher performance.

https://pmd.github.io/pmd-6.3.0/pmd_userdocs_getting_started.html#incremental-analysis

Is there a solution for this yet?

**Comment by mr-archano** [comment]
Hi @FHellmann, this plugin under the hood applies the built-in PMD plugin from Gradle, and lets you configure the tool as you would normally do without using it. Looking at the page you linked it looks like incremental analysis should be automatically supported by recent versions of PMD, but looking at the last version of Gradle it seems like the support for this feature didn't make the release yet because of some issue:
- https://github.com/gradle/gradle/pull/2223
- https://github.com/gradle/gradle/pull/3125

Given we are relying on the built-in `PmdPlugin` from Gradle we need to wait for those issues to be solved, but hopefully a future version of Gradle will let you just enable that (we keep the original `pmd` extension, we just add couple more utilities to it).

**Comment by FHellmann** [comment]
@mr-archano thank you for your fast reply. Hopfuly these issues will be fixed soon.

**Comment by bitsydarel** [comment]
Those issues seems to have been resolved. Any plans on adding this to the next release?

**Comment by tasomaniac** [comment]
Looks like Gradle's support was reverted. Here is the most recent issue. It is still open. 

https://github.com/gradle/gradle/issues/2862

**Comment by Cinderhaze** [comment]
This looks like it was resolved in gradle 5.6 - https://docs.gradle.org/5.6/release-notes.html#support-for-pmd-incremental-analysis - It was merged in commit https://github.com/gradle/gradle/commit/9093bb01eeecda38e9ec8465295c9497b6ff1924

**Comment by tasomaniac** [comment]
I'm not sure if this plugin should enable it by default. What is nice about this plugin is that you can configure every single property provided by the underlying plugins. Adding below will enable it for you if you use Gradle 5.6

```
pmd {
    incrementalAnalysis = true
}
```

What we can do is to provide this into our documentation.
