### ISSUE TITLE
Multiple different ' ktlint' plugin references

### ISSUE THREAD

**Issue by lgvalle** [novoda/gradle-static-analysis-plugin#135]
I'm was going through the project documentation and code to setup a new ktlint integration and I found three different references to ktlint plugins:

* `org.jlleitschuh.gradle.ktlint` in: https://github.com/novoda/gradle-static-analysis-plugin/blob/master/plugin/src/main/groovy/com/novoda/staticanalysis/internal/ktlint/KtlintConfigurator.groovy#L15 
* `org.jmailen.gradle:kotlinter-gradle` in : https://github.com/novoda/gradle-static-analysis-plugin/blob/master/plugin/src/main/groovy/com/novoda/staticanalysis/internal/ktlint/KtlintConfigurator.groovy#L16)
* `com.github.shyiko:ktlint` in the first ktlint link in :  https://github.com/novoda/gradle-static-analysis-plugin/blob/master/docs/tools/ktlint.md and in the table in https://github.com/novoda/gradle-static-analysis-plugin/blob/master/docs/supported-tools.md

Which one is the recommended one? 
I believe only the first one is supported since is the one the configurator expects. If that the case we should ammend the documentation.

**Comment by mr-archano** [comment]
@lgvalle KtLint is a command line, standalone tool (no built-in Gradle support). The links in the docs are correct:
- `https://github.com/shyiko/ktlint` is the repo of the tool, as mentioned in [`README.md`](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/README.md#supported-tools), [docs/supported-tools.md](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/docs/supported-tools.md#supported-tools) and [docs/tools/ktlint](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/docs/tools/ktlint.md#ktlint)
- `https://github.com/JLLeitschuh/ktlint-gradle/` is the repo  of the support KtLint Gradle plugin, as mentioned in [docs/tools/ktlint.md](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/docs/tools/ktlint.md#important-setup-ktlint), where it's also explained the why of this choice.

It appears though that the error message in [`KtlintConfigurator.groovy#L16`](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/plugin/src/main/groovy/com/novoda/staticanalysis/internal/ktlint/KtlintConfigurator.groovy#L16) is mentioning the wrong Gradle plugin (it got uncaught since the introduction of support of KtLint in #110). It should be something easy to fix. Feel free to issue a PR :)

**Comment by tasomaniac** [comment]
Thanks @mr-archano

I was looking at those 2 plugins at the time to see which one is more suitable. I think this was a copy paste mistake. :) The error message seems to be wrong.

**Comment by mr-archano** [comment]
Fixed in #137

**Comment by lgvalle** [comment]
Thanks for the explanation & the fix @mr-archano 💯
