### ISSUE TITLE
Show total count of issues found

### ISSUE THREAD

**Issue by xrigau** [novoda/gradle-static-analysis-plugin#19]
Every time I go on a boyscout mission and fix some static analysis issues I end up with the number of issues for each analysis type, but I have to configure a threshold for the total number of issues:

```
> Checkstyle rule violations were found (58 errors, 43 warnings). See the reports at:
- file:///Users/xrigau/development/git/novoda/some-cool-project/app/build/reports/checkstyle/main.html
> Findbugs rule violations were found (9 errors, 6 warnings). See the reports at:
- file:///Users/xrigau/development/git/novoda/some-cool-project/app/build/reports/findbugs/coolprojectStaging.html
> PMD rule violations were found (11 errors, 13 warnings). See the reports at:
- file:///Users/xrigau/development/git/novoda/some-cool-project/app/build/reports/pmd/main.html
```

It'd be a lot easier if it printed a line such as:

```
Total: 78 errors, 62 warnings
```

So that I can update the thresholds after every boyscoutting more easily.

This wouldn't be needed if #18 was implemented

**Comment by mr-archano** [comment]
This can be easily added indipendently from #18. Let's do it 👍

**Comment by tasomaniac** [comment]
Regarding this, I was also thinking about merging results across sub-projects in a big Gradle project. 
Imagine a project with many modules, when a tool fails the build, it is hard to detekt which module it is. And reports are separated since they run individually on all projects.

Also in such scenario, `maxErrors` does not make much sense individually for each submodule. It would only makes sense when `maxErrors = 0` (simply because  `0 x noOfModules = 0`)

In past projects, I did the following to merge unitTest results. This is something provided by Gradle. I couldn't find an easy way to do the same for `lint` for example (i.e merging lint results from different modules)

Merging multiple unit test results:
```
  def testTasks = [...] // manual list of all test tasks

  task testReport(type: TestReport) {
    destinationDir = file("$buildDir/reports/allTests")
    reportOn { testTasks.collect { project.tasks.findByPath(it)*.binResultsDir } }
  }
```

**Comment by tasomaniac** [comment]
@xrigau today is your lucky day

**Comment by xrigau** [comment]
EXCITEMENT!

![](http://forgifs.com/gallery/d/213102-1/Baby-omg-reactions.gif)

**Comment by tasomaniac** [comment]
I thought you would have 0 warnings and error by now :troll:

**Comment by xrigau** [comment]
![](https://i.imgur.com/XgnfHrr.gif)
