### ISSUE TITLE
PMD and Checkstyle doesn't found sources in Android project

### ISSUE THREAD

**Issue by kirich1409** [novoda/gradle-static-analysis-plugin#195]
PMD check can't found sources for any build variant in Android project

**Comment by tasomaniac** [comment]
Hi, the sample app has PMD integration. Can you check if you can reproduce
the issue there?

**Comment by mr-archano** [comment]
@kirich1409 any news about this? As mentioned above the demo app has PMD setup that you can use as reference. Also this integration test has been specifically designed to ensure the plugin works with Android variants: https://github.com/novoda/gradle-static-analysis-plugin/blob/master/plugin/src/test/groovy/com/novoda/staticanalysis/internal/pmd/PmdAndroidVariantIntegrationTest.groovy

Could you take another look and let us know?

**Comment by kirich1409** [comment]
Sorry, but I have no possibility to check that

**Comment by mr-archano** [comment]
It seems like we don't have enough context to understand or reproduce the issue.
As stated above we are already ensuring that Android variants work correctly with PMD, so I am sorry but I would consider that the issue is somewhere else.
Feel free to re-open the issue if you will manage to either provide a sample or a [test](https://github.com/novoda/gradle-static-analysis-plugin/blob/master/plugin/src/test/groovy/com/novoda/staticanalysis/internal/pmd) reproducing the issue.
